jwt:
  authenticationToken:
    expirationTime: "${ JWT_AUTHENTICATION_TOKEN_EXPIRATION_TIME }"
    secret: "${ JWT_AUTHENTICATION_TOKEN_SECRET }"
  refreshToken:
    expirationTime: "${ JWT_REFRESH_TOKEN_EXPIRATION_TIME }"
    secret: "${ JWT_REFRESH_TOKEN_SECRET }"

server:
  port: "${ SERVER_PORT }"

spring:
  database:
    driverClassName: "${ SPRING_DATABASE_DRIVER_CLASS_NAME }"
  datasource:
    url: "jdbc:postgresql://postgres:${ secrets.DATABASE_PORT }/${ DATABASE_NAME }"
    username: "${ DATABASE_USERNAME }"
    password: "${ DATABASE_PASSWORD }"