name: Tests, build and push docker container on PR in dev
run-name: ${{ github.actor }} is pushing docker container🚀

on:
  pull_request:
    branches:
      - 'dev'

jobs:
  test-build-push:
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: ${{ secrets.DATABASE_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          POSTGRES_PORT: 5432
          POSTGRES_DB: ${{ secrets.DATABASE_NAME }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Get project name and version
        id: get-data
        run: |
          cd ./to-do-list
          echo "Project name is $(./gradlew -q projectName)"
          echo "Project version is $(./gradlew -q projectVersion)"
          echo "PROJECT_VERSION=$(./gradlew -q projectVersion)" >> $GITHUB_OUTPUT
          echo "PROJECT_NAME=$(./gradlew -q projectName)" >> $GITHUB_OUTPUT

      - name: Secrets Substitution
        uses: Lambdaspire/action-substitute-secrets-in-file@v1.0.0
        with:
          file: to-do-list/src/main/resources/application.yml
          tokenPattern: ${ TOKEN }
          secretsJson: ${{ toJSON(secrets) }}

      - name: Test Secrets Substitution
        uses: Lambdaspire/action-substitute-secrets-in-file@v1.0.0
        with:
          file: to-do-list/src/test/resources/application.yml
          tokenPattern: ${ TOKEN }
          secretsJson: ${{ toJSON(secrets) }}

      - name: Test
        run: |
          cd ./to-do-list
          chmod +x ./gradlew
          ./gradlew test

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          target: dev
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.get-data.outputs.PROJECT_NAME }}:${{ steps.get-data.outputs.PROJECT_VERSION }}-dev